version: '2.1'

services:
    logstash:
        extends:
            file: common.yml
            service: common
        container_name: logstash
        image: logstash:5.6
        volumes:
            - ./etc/logstash/conf.d:/etc/logstash/conf.d
        command: -f /etc/logstash/conf.d -r
        environment:
            LS_JAVA_OPTS: "-Xmx256m -Xms256m"
            XPACK_MONITORING_ENABLED: "false"
        ports:
            - '514:10514/udp'
        mem_limit: 512m

    elasticsearch:
        extends:
            file: common.yml
            service: common
        container_name: elasticsearch
        image: elasticsearch:5.6
        volumes:
            - ./data:/usr/share/elasticsearch/data
        environment:
            ES_JAVA_OPTS: "-Xms512m -Xmx512m"
        ports:
            - '9200:9200'
        mem_limit: 1g

    kibana:
        extends:
            file: common.yml
            service: common
        container_name: kibana
        image: kibana:5.6
        environment:
            ELASTICSEARCH_HOSTS: http://elasticsearch:9200
            XPACK_MONITORING_ENABLED: "false"
        ports:
            - "80:5601"    

    