version: '2.1'

services:
    filebeat:
        extends:
            file: common.yml
            service: common
        container_name: filebeat
        image: docker.elastic.co/beats/filebeat:5.6.16
        volumes:
            - ./etc/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
            - /var/log/:/opt/filebeat/log/
        network_mode: host
        user: root